### ISSUE TITLE
ai wont learn

### ISSUE THREAD

**Issue by mellomlia** [AqwamCreates/DataPredict#3]
hey, it seems like the sword ai u made, doesnt learn to go towards eachother to attack, is there anything im doing wrong? if so please tell me, thank you.

**Comment by AqwamCreates** [comment]
Sometimes, all you need to do is to reset the model parameters. Reinforcement learning can be quite tricky.

**Comment by mellomlia** [comment]
How do i do that, and when do i know when to? Also keep up the good work man

**Comment by AqwamCreates** [comment]
In the main script, just comment the line 95 and 119 and run the game. Then uncomment those after running the game. That should reset the model parameters.

Also, you may want to replace the DataPredict library to a recent one because I made some calculation mistakes there. It may have contributed to slower training time.

**Comment by mellomlia** [comment]
Do i just put the free model and replace it and put it in the same places? Or will it be updated in the rbxl

**Comment by AqwamCreates** [comment]
Yeah you can do that.

**Comment by AqwamCreates** [comment]
You can do any of those either way.

**Comment by AqwamCreates** [comment]
Just get the new version of the place.

**Comment by mellomlia** [comment]
It doesnt seem to work at all now, maybe u removed something on accident cause the bots doesnt spawn at all

**Comment by AqwamCreates** [comment]
I made minor fixes. You can update it to newest one. All I had to do was to fix the naming of the library under the "ServerScriptService" folder, which should be an easy fix for you to do.

**Comment by mellomlia** [comment]
they now seem to be working, but quick question. how long does it take for them to learn to get close to eachother?

**Comment by mellomlia** [comment]
so far the ais hasnt learned to move towards eachother

**Comment by AqwamCreates** [comment]
Well, someone removed the "jump" ability from the Ais, and got the result within 10-15 minutes.

For me, I got it within 2 hours.

**Comment by mellomlia** [comment]
oh okay, what do you think i should do

**Comment by mellomlia** [comment]
and how do i remove the jump

**Comment by mellomlia** [comment]
what i tried to do was to shrink the box

**Comment by mellomlia** [comment]
hoe aobut i turn th jump off, and turn it on after they've learned to get close too eahcother

**Comment by mellomlia** [comment]
my goal is to make an ai that learns to walk, ive seen so many of them on yt and wondered if i could make it in roblox aha

**Comment by mellomlia** [comment]
so its been like 7 hours and still hasnt learned, ive tried reseting the parameters too, any solutions?

**Comment by AqwamCreates** [comment]
I have updated the files. It now should start showing the agents going closer to each other within 5 minutes. Otherwise, you need to reset the parameters if it exceeds that.

**Comment by mellomlia** [comment]
alright, what was wrong with it before that?

**Comment by mellomlia** [comment]
ye now its working
nice!

**Comment by mellomlia** [comment]
by the way, is senses supposed to be disabled?

**Comment by mellomlia** [comment]
so uh, it seems like they're only facing the wall, idk if i have to wait a  lil tho

**Comment by mellomlia** [comment]
and they keep spinning

**Comment by mellomlia** [comment]
is the spinning issue common?

**Comment by mellomlia** [comment]
or the walking into wall issue?

**Comment by AqwamCreates** [comment]
Yes, it was common. You may need to play around how the AI is rewarded in the "Senses" script.

Also yes, "Senses" script is supposed to be disabled, but it gets enabled when the AI spawns.

**Comment by mellomlia** [comment]
ive let it run for about 2 hours now, and still not learned to walk towards eachother

**Comment by mellomlia** [comment]
ive also resetted the paragraphs, doesnt seem to work either

**Comment by mellomlia** [comment]
u sohuld make it so it gets rewarded if it gets closer

**Comment by mellomlia** [comment]
btw, i found another version of ur script that u maybe could take a look at if u want

**Comment by mellomlia** [comment]
idk why but it just walks into walls and walks random ways

**Comment by mellomlia** [comment]
is there anything im missing when setting it up?

**Comment by mellomlia** [comment]
btw, i found an ai that u could use as inspo, it has the same problem tho. it doesnt learn to get towards the other bot, if ur interested, ill send u the rbxl

**Comment by mellomlia** [comment]
oh btw, a question how do i make ai learn to balance or walk?

**Comment by mellomlia** [comment]
Hey, i saw that you updated the rbxl, what did you add?

**Comment by mellomlia** [comment]
also, why is it that the ais sometimes just pause for like 1 sec and then continue?

**Comment by AqwamCreates** [comment]
You're setting it correctly just fine. Its just that again, reinforcement learning can be quite tricky.

**Comment by AqwamCreates** [comment]
You're doing it just fine. It is just that reinforcement learning is quite tricky.
